on: [push]
name: Azure ARM
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - uses: actions/checkout@main

    # Authenticate to Az CLI using OIDC
    - name: 'Az CLI login'
      uses: azure/login@v1
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS }}'

      # Deploy Bicep file
    - name: deploy
      uses: azure/arm-deploy@v1
      with:
        InlineScript: |
          az deployment sub validate \
          --name validate-${{ github.run_id }} \
          --template-file main.bicep \
          --location $LOCATION
